version: 2
jobs:
  build-and-test:
    docker:
    - image: circleci/python:latest
    steps:
    - checkout
    - run:
        command: make install
        name: Make Install
workflows:
  main:
    jobs:
    - build-and-test
  version: 2